### PR TITLE
Add zh_CN locale

### PR DESCRIPTION
**Pull request by yfdyh000**
`"Copied!"` is missing.
accesskeys is missing.
Add picking the left tabs?

### CODE REVIEW

**Comment by eight04** [comment]
> "Copied!" is missing.

Added in a744ff9

> accesskeys is missing.

Do you mean Ctrl/Shift/Alt? I thought there is no need to translate them.

> Add picking the left tabs?

Currently there is no such feature. We can open a new issue for discussion if you need it.

BTW, I have no experience implementing i18n stuff. What is you workflow to translate extensions? Currently I'm trying to put `messages.json` on Transifex. Would it help?
https://www.transifex.com/image-picka/image-picka/dashboard/

**Comment by eight04** [comment]
After merging this PR I'll push it to Transifex too.

**Comment by yfdyh000** [comment]
> Do you mean Ctrl/Shift/Alt? I thought there is no need to translate them.

No, I mean adding accesskeys to buttons, allowing keyboard-only operation.

> BTW, I have no experience implementing i18n stuff. What is you workflow to translate extensions? Currently I'm trying to put messages.json on Transifex. Would it help?

This is good.

**Comment by eight04** [comment]
Would you like to add `pickerActionCopyUrlCopied` message? Or I will merge it directly.

**Comment by eight04** [comment]
👍

**Pull request merged**
